<?php
// ma.php - Click Wall display functionality
header('Content-Type: application/javascript');
?>
// Click Wall functionality - Generated by ma.php
function showClickWall() {
// Get gtg value from localStorage (set by gtg.php validation)
const gtg = localStorage.getItem('gtg');
const gtgTraffic = localStorage.getItem('gtgTraffic') || 'true';
const medicareAnswer = localStorage.getItem('medicareAnswer') || '';

// Show click wall if traffic is legitimate AND user answered "Yes" to Medicare
// gtg should be null for legitimate traffic (not sent to Ringba)
if ((gtg === null || gtg === 'null') && gtgTraffic === 'true' && medicareAnswer === 'Yes') {
const clickwallSection = document.getElementById('clickwall-section');
const loader = document.getElementById('clickwall-loader');
const iframeContainer = document.getElementById('clickwall-iframe-container');
const iframe = document.getElementById('clickwall-iframe');

if (clickwallSection) {
clickwallSection.style.display = 'block';

// Auto-scroll to click wall and center it
setTimeout(function() {
clickwallSection.scrollIntoView({
behavior: 'smooth',
block: 'center'
});
}, 100);

// Show loader initially
if (loader) {
loader.style.display = 'flex';
}
if (iframeContainer) {
iframeContainer.style.display = 'none';
}

// Load iframe after a short delay
setTimeout(function() {
if (iframe) {
// Get mb parameter from current URL
const urlParams = new URLSearchParams(window.location.search);
const mbValue = urlParams.get('mb') || '';

// Set iframe source with mb parameter
iframe.src = 'https://policyfinds.com/sqc2026/iframe.html' + (mbValue ? '?mb=' + encodeURIComponent(mbValue) : '');

iframe.onload = function() {
// Hide loader and show iframe when loaded
if (loader) {
loader.style.display = 'none';
}
if (iframeContainer) {
iframeContainer.style.display = 'block';
}
};
}
}, 1000);
}
}
}

// Use event delegation to handle phone button clicks (works even if element is hidden initially)
document.addEventListener('click', function(e) {
const target = e.target.closest('#phone-number');
if (target) {
// Show click wall after 7 seconds
setTimeout(function() {
showClickWall();
}, 7000);
}
});